inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod 'RedditKit', :path => '../'
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
